"""`homelabsage init` — interactive config bootstrap.

Writes a minimal `config.yaml` with safe defaults so a fresh install
can scan + analyse + persist without the user reading the full
config schema. The web wizard remains the long-form path; this CLI
is the "I just installed this and want to verify it runs" shortcut.

Prompts:
  - LLM endpoint (skip → leave empty, web wizard later)
  - LLM model name
  - Storage directory (defaults to ./data)
  - Whether to enable Docker plugin (default yes)

Won't overwrite an existing config unless `--force`.
"""

from __future__ import annotations

from pathlib import Path

import typer

from ._common import VERBOSE_OPT, app, console, setup_logging

_PATH_ARG = typer.Argument(
    Path("config.yaml"),
    help="Where to write the config (defaults to ./config.yaml).",
)


_DEFAULT_TEMPLATE = """# HomelabSage — generated by `homelabsage init`.
# See https://github.com/jlp9989-sudo/HomelabSage for the full schema.

llm:
  provider: openai
  endpoint: {endpoint}
  model: {model}

storage:
  database_path: {db_path}

sources:
  docker:
    enabled: {docker_enabled}

notes:
  notes_dir: {notes_dir}

scheduler:
  enabled: true
  cron: "0 9 * * *"
  timezone: UTC
"""


@app.command(name="init")
def init_cmd(
    path: Path = _PATH_ARG,
    force: bool = typer.Option(
        False, "--force",
        help="Overwrite the file even if it already exists.",
    ),
    non_interactive: bool = typer.Option(
        False, "--non-interactive",
        help="Skip prompts; use defaults (handy for CI bootstraps).",
    ),
    verbose: bool = VERBOSE_OPT,
) -> None:
    """Bootstrap a minimal `config.yaml` interactively."""
    setup_logging(verbose)
    if path.exists() and not force:
        console.print(
            f"[red]{path} already exists.[/red] Pass --force to overwrite."
        )
        raise SystemExit(2)

    defaults = {
        "endpoint": "",
        "model": "gpt-oss-20b",
        "db_path": "./data/homelabsage.db",
        "docker_enabled": "true",
        "notes_dir": "./notes",
    }
    if non_interactive:
        values = defaults
    else:
        console.print("[bold]HomelabSage — minimal config bootstrap[/bold]\n")
        console.print(
            "[dim]Press Enter to accept the default in [brackets].[/dim]\n"
        )
        values = {
            "endpoint": typer.prompt(
                "LLM endpoint (e.g. http://192.168.1.10:11434/v1)",
                default=defaults["endpoint"], show_default=False,
            ),
            "model": typer.prompt(
                "LLM model name", default=defaults["model"],
            ),
            "db_path": typer.prompt(
                "SQLite database path", default=defaults["db_path"],
            ),
            "docker_enabled": "true" if typer.confirm(
                "Enable the Docker plugin?", default=True,
            ) else "false",
            "notes_dir": typer.prompt(
                "Notes directory (for audit.md + curator notes)",
                default=defaults["notes_dir"],
            ),
        }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_DEFAULT_TEMPLATE.format(**values))
    console.print(f"\n[green]Wrote {path}[/green]")
    console.print(
        "Next: `homelabsage check --config "
        f"{path}` to verify the plugin set."
    )
    raise SystemExit(0)
