"""Data models shared by core, plugins and outputs."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class Severity(StrEnum):
    """Severity assigned by the LLM to an update."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    INFO = "info"

    @property
    def order(self) -> int:
        return {"info": 0, "medium": 1, "high": 2, "critical": 3}[self.value]


class UpdateStatus(StrEnum):
    """Tracking state of a detected update in the local DB."""

    NEW = "new"
    ANALYZED = "analyzed"
    APPLIED = "applied"
    DISMISSED = "dismissed"
    FAILED = "failed"


class InterviewStatus(StrEnum):
    """Tracking state of a curator interview question."""

    PENDING = "pending"
    ANSWERED = "answered"
    DISMISSED = "dismissed"


class Update(BaseModel):
    """A single available update detected by a plugin.

    `source` is the plugin id (e.g. "docker", "homeassistant").
    `subject` is what is being updated (e.g. "OpenClaw" container,
    "core" for HA Core, "hacs:integrations/foo" for HACS, etc).
    """

    source: str
    subject: str
    current_version: str
    new_version: str
    release_url: str | None = None
    release_notes: str | None = None
    # Free-form context the plugin wants to forward to the LLM
    # (config snippets, install method, etc).
    context: dict[str, Any] = Field(default_factory=dict)


class Analysis(BaseModel):
    """LLM analysis of an Update.

    All fields are produced by the LLM following a strict JSON schema.
    """

    severity: Severity
    summary: str
    breaking_changes: list[str] = Field(default_factory=list)
    config_obsolete: list[str] = Field(default_factory=list)
    new_features_relevant: list[str] = Field(default_factory=list)
    action_required: bool = False
    recommended_action: str | None = None


class AnalyzedUpdate(BaseModel):
    """An Update plus its Analysis, ready to be persisted and routed to outputs."""

    update: Update
    analysis: Analysis | None = None
    status: UpdateStatus = UpdateStatus.NEW
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    analyzed_at: datetime | None = None
    # Cache of the Notion page id once we have created/found it. Lets the
    # Notion output PATCH instead of POST and prevents duplicate rows when
    # the same id is re-emitted (e.g. analysis was None on a prior run).
    notion_page_id: str | None = None

    @property
    def id(self) -> str:
        """Stable identifier across runs: source + subject + new_version."""
        return f"{self.update.source}:{self.update.subject}:{self.update.new_version}"


class InterviewQuestion(BaseModel):
    """A clarification the curator needs from the user before it can write a
    useful note for a container.

    Created when the LLM emits the Rule 7 fallback (no purpose stated yet —
    fill in). `image_digest_short` records which build of the image the
    question was raised for; if the image is rebuilt later the question stays
    valid (the purpose typically does not depend on the image hash) but the
    answer is invalidated and a fresh question is added if the new run also
    fails Rule 7.
    """

    id: int | None = None
    container_name: str
    image_digest_short: str
    question_text: str
    # The LLM's best guess at what this software does, generated by a second
    # prompt right after the Rule 7 fallback. Used to prefill the answer
    # textarea — the user typically edits a single word or confirms it.
    suggested_text: str | None = None
    answer_text: str | None = None
    status: InterviewStatus = InterviewStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    answered_at: datetime | None = None
